### ISSUE TITLE
Using ssh for git pushes

### ISSUE THREAD

**Issue by peonicles** [ga-students/wdi-sg-organisers#18]
Since we're now (somewhat) familiar with git / github, it might be worthwhile to create ssh key pairs for authentication with github / bitbucket.

https://help.github.com/articles/generating-ssh-keys/

**Comment by cbas** [comment]
Oddly enough GitHub documentation [recommends using HTTPS over SSH](https://help.github.com/articles/set-up-git/#connecting-over-https-recommended). This is especially strange since the GitHub Desktop client itself installs a key pair. Maybe because SSH causes too many customer support headaches? [Who knows.](http://stackoverflow.com/questions/11041729/why-does-github-recommend-https-vs-ssh)

To avoid the repeated password prompts (for HTTPS) it's useful to configure the [credential helper](https://help.github.com/articles/caching-your-github-password-in-git/).
